


-- 创建搜索记录表
CREATE TABLE IF NOT EXISTS TBS_INFO_HISTORY (
    ID SERIAL PRIMARY KEY,
    HISTORY_CONTENT TEXT,   --搜索内容
    SEARCH_EXT	INT     --搜索扩展信息
);

-- 创建公司查询表
CREATE TABLE IF NOT EXISTS TBS_INFO_COMPANY (
    ID SERIAL PRIMARY KEY,
    COMPANY_NAME TEXT,	--公司名
    COMPANY_REG_DATE TEXT,	--注册时间
    COMPANY_REG_EMAIL TEXT,	--注册邮箱
    COMPANY_SHAREHOLDER TEXT,	--股东
    COMPANY_ACTIVE TEXT,	--运营状态
    COMPANY_URL TEXT,	--详细网址信息
    SEARCH_EXT	INT	--搜索扩展信息
)


-- 创建股东信息表
CREATE TABLE IF NOT EXISTS TBS_INFO_SHAREHOLDER (
    ID SERIAL PRIMARY KEY,
    SHAREHOLDER_NAME TEXT, 	--股东名称
    SHAREHOLDER_TYPE TEXT, 	--股东类型
    SHAREHOLDER_MONEY TEXT, 	--出缴金额
    SHAREHOLDER_PROPORTION TEXT, 	--持股比例
    SHAREHOLDER_DATE TEXT, 	--认缴出资日期
    SHAREHOLDER_FLOAT TEXT, 	--增减情况
    SEARCH_EXT	INT	--搜索扩展信息
)


-- 创建对外投资表
CREATE TABLE IF NOT EXISTS TBS_INFO_INVESTMENT (
    ID SERIAL PRIMARY KEY,
    INVESTMENT_COMPANY TEXT, 	--被投资企业名称
    INVESTMENT_PERSON TEXT, 	--法人
    INVESTMENT_PROPORTION TEXT, 	--投资比例
    INVESTMENT_MONEY TEXT, 	--投资数额
    INVESTMENT_DATE TEXT, 	--成立日期
    INVESTMENT_PRODUCT TEXT, 	--关联产品
    SEARCH_EXT	INT	--搜索扩展信息
)


-- 创建分支机构表
CREATE TABLE IF NOT EXISTS TBS_INFO_BRANCH (
    ID SERIAL PRIMARY KEY,
    BRANCH_NAME TEXT, 	--分支机构名称
    BRANCH_STATE TEXT, 	--经营状态
    BRANCH_PERSON TEXT, 	--负责人
    BRANCH_DATE TEXT, 	--成立日期
    SEARCH_EXT	INT	--搜索扩展信息
)
-- 创建网站备案表
CREATE TABLE IF NOT EXISTS TBS_INFO_BA (
    ID SERIAL PRIMARY KEY,
    BA_HOME TEXT, 	--网站地址
    BA_SITE TEXT, 		--网站名称
    BA_DOMAIN TEXT, 	--域名
    BA_DATE TEXT, 		--审核日期
    BA_NUMBER TEXT, 	--网站备案/许可证号
    SEARCH_EXT	INT	--搜索扩展信息
)

-- 创建搜索扩展信息表
CREATE TABLE IF NOT EXISTS TBS_INFO_SEARCH_EXT (
    ID SERIAL PRIMARY KEY,
    COMPANY_FIRST_DATE TEXT, 	--第一次记录时间
    COMPANY_LAST_DATE TEXT, 	--最后一次记录时间
    COMPANY_DATE_TYPE TEXT, 	--使用什么类型进行搜索（天眼查、爱企查）
    COMPANY_ID TEXT, 	--公司ID
)
